## 1. Configuração do ambiente

In [103]:
# Essa só deve ser executada se for analisar no VS Code.
# Precisa criar o ambiente virtual do Python (.venv) e os requirements.
# Depois de feito as duas cirações acima, roda essa linha para instalar as dependências.
# %pip install -r requirements.txt

In [104]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [105]:
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl
import sys
import os

## 2. Problema e perguntas

## 3. Carga dos dados

In [106]:
caminho_drive = '/content/drive/MyDrive/analise_sinistros_transito_amc/Análises/0. Dataset/Cópia de 1_sinistros_transito_2015_2024_original.csv'
df = pd.read_csv(caminho_drive)

/tmp/ipykernel_3712/388821255.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_drive)

## 4. Primeira inspeção

In [107]:
df.shape

(130823, 27)

In [108]:
df.head()

,COD_ACIDENTE,DIA,MES,ANO,HORA,LOG1,LOG2,NUMERO,LATITUDE,LONGITUDE,...,ILESOS,AUTOMOVEL,ONIBUS,BICICLETA,CAMINHAO,MICROONIBUS,CICLOMOTOR,MOTOCICLETA,TRACAOANIMAL,TREM
0,256301,1,1,2015,00:11:00,"AVENIDA DR SILAS MUNGUBA,",",",NaN,-3.782338,-38.555506,...,0,1,0,0,0,0,0,1,0,0
1,259748,1,1,2015,00:14:00,"RUA GONCALO SOUTO,",",",NaN,-3.766471,-38.529866,...,0,0,0,0,0,0,0,0,0,0
2,256302,1,1,2015,00:31:00,"RUA ANTONIO POMPEU,","RUA GAL SAMPAIO,",NaN,-3.734083,-38.532908,...,0,0,1,1,0,0,0,0,0,0
3,247611,1,1,2015,01:40:00,"RUA TEN BENEVOLO,","AVENIDA RUI BARBOSA,",NaN,-3.728685,-38.507048,...,0,0,1,0,0,0,0,1,0,0
4,256214,1,1,2015,02:10:00,"AVENIDA CASTELO DE CASTRO, 680",",",680.0,-3.835387,-38.521641,...,0,0,0,0,0,0,0,1,0,0

In [109]:
df.tail()

,COD_ACIDENTE,DIA,MES,ANO,HORA,LOG1,LOG2,NUMERO,LATITUDE,LONGITUDE,...,ILESOS,AUTOMOVEL,ONIBUS,BICICLETA,CAMINHAO,MICROONIBUS,CICLOMOTOR,MOTOCICLETA,TRACAOANIMAL,TREM
130818,LDP3638,31,12,2024,18:27:41,Rua Coronel De Queiroz,Não informado,620.0,-3.834058,-38.567904,...,0,0,0,1,0,0,0,0,0,0
130819,SGR8451,31,12,2024,18:50:51,Avenida Sargento Herminio Sampaio,Não informado,554.0,-3.724648,-38.546441,...,0,1,0,1,0,0,0,0,0,0
130820,BXT7020,31,12,2024,19:30:00,Avenida Sargento Hermínio Sampaio,RUA PDE ANCHIETA,1130.0,-3.724633,-38.551079,...,0,0,0,0,0,0,0,0,0,0
130821,WDE7928,31,12,2024,20:10:00,Rua Tenente Jose Newton,RUA VASCO DE ATAIDE,104.0,-3.823448,-38.491546,...,1,1,0,0,0,0,0,1,0,0
130822,ECB9300,31,12,2024,23:07:56,Creusa Rocha,Não informado,311.0,-3.721356,-38.591703,...,0,0,0,0,0,0,0,2,0,0

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130823 entries, 0 to 130822
Data columns (total 27 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   COD_ACIDENTE     130820 non-null  object
 1   DIA              130823 non-null  int64
 2   MES              130823 non-null  int64
 3   ANO              130823 non-null  int64
 4   HORA             130823 non-null  object
 5   LOG1             130823 non-null  object
 6   LOG2             130823 non-null  object
 7   NUMERO           65434 non-null   float64
 8   LATITUDE         130823 non-null  float64
 9   LONGITUDE        130823 non-null  float64
 10  TIPOCRUZAMENTO   130823 non-null  object
 11  CONTROLETRAFEGO  130823 non-null  object
 12  USOSOLO          130823 non-null  object
 13  NATUREZA         130823 non-null  object
 14  SEVERIDADE       130823 non-null  object
 15  MORTOS           130823 non-null  int64
 16  FERIDOS          130823 non-null  int64
 17  ILESOS           130823 non-null  int64
 18  AUTOMOVEL        130823 non-null  int64
 19  ONIBUS           130823 non-null  int64
 20  BICICLETA        130823 non-null  int64
 21  CAMINHAO         130823 non-null  int64
 22  MICROONIBUS      130823 non-null  int64
 23  CICLOMOTOR       130823 non-null  int64
 24  MOTOCICLETA      130823 non-null  int64
 25  TRACAOANIMAL     130823 non-null  int64
 26  TREM             130823 non-null  int64
dtypes: float64(3), int64(15), object(9)
memory usage: 26.9+ MB

In [111]:
df.describe()

,DIA,MES,ANO,NUMERO,LATITUDE,LONGITUDE,MORTOS,FERIDOS,ILESOS,AUTOMOVEL,ONIBUS,BICICLETA,CAMINHAO,MICROONIBUS,CICLOMOTOR,MOTOCICLETA,TRACAOANIMAL,TREM
count,130823.000000,130823.000000,130823.000000,6.543400e+04,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.00000
mean,15.428946,6.502442,2019.019790,2.245865e+03,-3.767022,-38.539138,0.015181,1.069758,0.527721,0.838056,0.048822,0.043524,0.029720,0.005756,0.004418,0.648212,0.000099,0.00042
std,8.759829,3.469298,2.984652,7.603337e+04,0.037304,0.039769,0.126089,0.702956,0.819732,0.773450,0.218945,0.204447,0.173949,0.075952,0.066553,0.610408,0.009968,0.02050
min,1.000000,1.000000,2015.000000,0.000000e+00,-3.896179,-38.637996,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,8.000000,3.000000,2016.000000,4.420000e+02,-3.793945,-38.570794,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,15.000000,6.000000,2019.000000,1.127000e+03,-3.760579,-38.539369,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000
75%,23.000000,10.000000,2022.000000,2.520000e+03,-3.736271,-38.506470,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000
max,31.000000,12.000000,2024.000000,1.943194e+07,-3.693333,-38.410074,3.000000,26.000000,8.000000,12.000000,3.000000,3.000000,4.000000,2.000000,2.000000,6.000000,1.000000,1.00000

In [112]:
df.describe(include="object")

,COD_ACIDENTE,HORA,LOG1,LOG2,TIPOCRUZAMENTO,CONTROLETRAFEGO,USOSOLO,NATUREZA,SEVERIDADE
count,130820,130823,130823,130823,130823,130823,130823,130823,130823
unique,130820,23232,41243,7793,14,16,3,20,4
top,ECB9300,16:00:00,"RD CE-040,",",",Meio de Quadra,Não informado,Longo da via,Colisão,Ferido
freq,1,723,2035,49482,48457,78372,63227,58544,94599

## 5. Qualidade dos dados

In [113]:
colunas = ["TIPOCRUZAMENTO", "CONTROLETRAFEGO", "USOSOLO", "NATUREZA", "SEVERIDADE"]

nao_informado = df[colunas].apply(lambda s: s.str.strip().str.lower() == "não informado")

resumo = pd.DataFrame({
    "nao_informado": nao_informado.sum(),
    "total": len(df),
    "percentual": (nao_informado.mean() * 100).round(2),
})
resumo

                 nao_informado   total  percentual
TIPOCRUZAMENTO           16296  130823       12.46
CONTROLETRAFEGO          78376  130823       59.91
USOSOLO                  28515  130823       21.80
NATUREZA                  1254  130823        0.96
SEVERIDADE                9242  130823        7.06

## 6. Limpeza e preparação

A partir daqui o `df` deixa de ser a base original e passa a ser a base tratada.

A função `tratar` (arquivo `scripts/tratar_base.py`, detalhes em `tratamento_dados.md`) faz a primeira parte da limpeza:

- unifica `DIA`, `MES`, `ANO` e `HORA` em `DATA E HORA`;
- substitui `LOG1`, `LOG2` e `NUMERO` por `BAIRRO` e `RUA`, obtidas das coordenadas;
- mantém `COD_ACIDENTE` como texto.

In [114]:
import sys
import os

# Caminho real da sua pasta de scripts no Google Drive
caminho_real_scripts = '/content/drive/MyDrive/analise_sinistros_transito_amc/Análises/0. Scripts'

# Criamos um link simbólico chamado 'scripts' apontando para '0. Scripts'
# Isso resolve a importação interna 'from scripts.localizacao ...' de forma limpa!
link_atalho = '/content/scripts'

if os.path.exists(caminho_real_scripts):
    # Se o atalho antigo existir ou for um link quebrado, removemos para recriar com segurança
    if os.path.islink(link_atalho) or os.path.exists(link_atalho):
        try:
            os.unlink(link_atalho)
        except Exception:
            pass

    # Cria o link simbólico do sistema operacional
    os.symlink(caminho_real_scripts, link_atalho)

    # Adiciona o diretório atual '/content' ao sys.path para que o Python enxergue o atalho 'scripts'
    if '/content' not in sys.path:
        sys.path.append('/content')

    print("Atalho simbólico de '0. Scripts' para 'scripts' criado com sucesso!")
else:
    print(f"AVISO: A pasta original não foi encontrada no Drive: {caminho_real_scripts}")

# Agora a importação funcionará perfeitamente, mapeando todas as referências internas!
from scripts.tratar_base import tratar

Atalho simbólico de '0. Scripts' para 'scripts' criado com sucesso!

### Texto

Padronização das categorias: sem espaços sobrando e com só a primeira letra maiúscula, para unificar grafias como `Meio de Quadra`, `Meio De Quadra` e `Meio de quadra`.

In [115]:
categoricas = ["TIPOCRUZAMENTO", "CONTROLETRAFEGO", "USOSOLO", "NATUREZA", "SEVERIDADE"]

categorias_antes = df[categoricas].nunique()

for coluna in categoricas:
    df[coluna] = (
        df[coluna]
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .str.capitalize()
        .replace({"Duplo t": "Duplo T"})
    )

pd.DataFrame({"categorias_antes": categorias_antes, "categorias_depois": df[categoricas].nunique()})

                 categorias_antes  categorias_depois
TIPOCRUZAMENTO                 14                 10
CONTROLETRAFEGO                16                 13
USOSOLO                         3                  3
NATUREZA                       20                 20
SEVERIDADE                      4                  4

### Tipos

In [116]:
# Primeiro, executamos o tratamento dos dados utilizando a função importada para criar 'DATA E HORA' e 'BAIRRO'
df = tratar(caminho_drive)

# Agora as conversões de tipos e formatações adicionais funcionarão corretamente
df["COD_ACIDENTE"] = df["COD_ACIDENTE"].astype("string")
df["DATA E HORA"] = pd.to_datetime(df["DATA E HORA"])

df[categoricas + ["BAIRRO"]] = df[categoricas + ["BAIRRO"]].astype("category")
df["SEVERIDADE"] = df["SEVERIDADE"].cat.reorder_categories(
    ["Ileso", "Ferido", "Fatal", "Não informado"]
)

df.dtypes

COD_ACIDENTE       string[python]
DATA E HORA        datetime64[ns]
BAIRRO                   category
RUA                        object
LATITUDE                  float64
LONGITUDE                 float64
TIPOCRUZAMENTO           category
CONTROLETRAFEGO          category
USOSOLO                  category
NATUREZA                 category
SEVERIDADE               category
MORTOS                      int64
FERIDOS                     int64
ILESOS                      int64
AUTOMOVEL                   int64
ONIBUS                      int64
BICICLETA                   int64
CAMINHAO                    int64
MICROONIBUS                 int64
CICLOMOTOR                  int64
MOTOCICLETA                 int64
TRACAOANIMAL                int64
TREM                        int64
dtype: object

### Ausentes e duplicados

Decisão pendente.

### Novas variáveis

| Coluna | Como é calculada |
|---|---|
| `DIA_SEMANA` | Dia da semana de `DATA E HORA` (Segunda a Domingo). |
| `FIM_DE_SEMANA` | `True` para sábado e domingo. |
| `FAIXA_HORARIA` | Madrugada (0h–5h59), Manhã (6h–11h59), Tarde (12h–17h59), Noite (18h–23h59). |
| `TOTAL_VITIMAS` | `MORTOS` + `FERIDOS`. |
| `TOTAL_VEICULOS` | Soma das nove colunas de veículos. |

In [117]:
dias = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"]
dia = df["DATA E HORA"].dt.dayofweek

df["DIA_SEMANA"] = pd.Categorical.from_codes(dia, categories=dias, ordered=True)
df["FIM_DE_SEMANA"] = dia >= 5
df["FAIXA_HORARIA"] = pd.cut(
    df["DATA E HORA"].dt.hour,
    bins=[0, 6, 12, 18, 24],
    labels=["Madrugada", "Manhã", "Tarde", "Noite"],
    right=False,
)

veiculos = [
    "AUTOMOVEL", "ONIBUS", "BICICLETA", "CAMINHAO", "MICROONIBUS",
    "CICLOMOTOR", "MOTOCICLETA", "TRACAOANIMAL", "TREM",
]
df["TOTAL_VITIMAS"] = df["MORTOS"] + df["FERIDOS"]
df["TOTAL_VEICULOS"] = df[veiculos].sum(axis=1)

df[["DATA E HORA", "DIA_SEMANA", "FIM_DE_SEMANA", "FAIXA_HORARIA", "TOTAL_VITIMAS", "TOTAL_VEICULOS"]].head()

,DATA E HORA,DIA_SEMANA,FIM_DE_SEMANA,FAIXA_HORARIA,TOTAL_VITIMAS,TOTAL_VEICULOS
0,2015-01-01 00:11:00,Quinta,False,Madrugada,2,2
1,2015-01-01 00:14:00,Quinta,False,Madrugada,2,0
2,2015-01-01 00:31:00,Quinta,False,Madrugada,2,2
3,2015-01-01 01:40:00,Quinta,False,Madrugada,3,2
4,2015-01-01 02:10:00,Quinta,False,Madrugada,2,1

### Validação

In [118]:
# Definimos 'shape_antes' caso ela não tenha sido guardada no início do notebook
if 'shape_antes' not in locals() and 'shape_antes' not in globals():
    # O shape original do seu DataFrame (obtido na primeira inspeção) era (130823, 27)
    shape_antes = (130823, 27)

print("antes: ", shape_antes)
print("depois:", df.shape)

assert df.shape[0] == shape_antes[0], "O número de linhas mudou."

antes:  (130823, 27)
depois: (130823, 28)

In [119]:
df.head()

,COD_ACIDENTE,DATA E HORA,BAIRRO,RUA,LATITUDE,LONGITUDE,TIPOCRUZAMENTO,CONTROLETRAFEGO,USOSOLO,NATUREZA,...,MICROONIBUS,CICLOMOTOR,MOTOCICLETA,TRACAOANIMAL,TREM,DIA_SEMANA,FIM_DE_SEMANA,FAIXA_HORARIA,TOTAL_VITIMAS,TOTAL_VEICULOS
0,256301,2015-01-01 00:11:00,Parangaba,Avenida Doutor Silas Munguba,-3.782338,-38.555506,Meio de Quadra,Não informado,Longo da via,Colisão,...,0,0,1,0,0,Quinta,False,Madrugada,2,2
1,259748,2015-01-01 00:14:00,Vila União,Rua Gonçalo Souto,-3.766471,-38.529866,Meio de Quadra,Não informado,Longo da via,Colisão,...,0,0,0,0,0,Quinta,False,Madrugada,2,0
2,256302,2015-01-01 00:31:00,Centro,Rua Antônio Pompeu,-3.734083,-38.532908,Não informado,Não informado,Cruzamento,Colisão,...,0,0,0,0,0,Quinta,False,Madrugada,2,2
3,247611,2015-01-01 01:40:00,Meireles,Rua Tenente Benévolo,-3.728685,-38.507048,Cruz,Semáforo,Cruzamento,Colisão Transversal,...,0,0,1,0,0,Quinta,False,Madrugada,3,2
4,256214,2015-01-01 02:10:00,Jangurussu,Avenida Deputado Castelo de Castro,-3.835387,-38.521641,Meio de Quadra,Não informado,Longo da via,Queda,...,0,0,1,0,0,Quinta,False,Madrugada,2,1

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130823 entries, 0 to 130822
Data columns (total 28 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   COD_ACIDENTE     130820 non-null  string
 1   DATA E HORA      130823 non-null  datetime64[ns]
 2   BAIRRO           130749 non-null  category
 3   RUA              130823 non-null  object
 4   LATITUDE         130823 non-null  float64
 5   LONGITUDE        130823 non-null  float64
 6   TIPOCRUZAMENTO   130823 non-null  category
 7   CONTROLETRAFEGO  130823 non-null  category
 8   USOSOLO          130823 non-null  category
 9   NATUREZA         130823 non-null  category
 10  SEVERIDADE       130823 non-null  category
 11  MORTOS           130823 non-null  int64
 12  FERIDOS          130823 non-null  int64
 13  ILESOS           130823 non-null  int64
 14  AUTOMOVEL        130823 non-null  int64
 15  ONIBUS           130823 non-null  int64
 16  BICICLETA        130823 non-null  int64
 17  CAMINHAO         130823 non-null  int64
 18  MICROONIBUS      130823 non-null  int64
 19  CICLOMOTOR       130823 non-null  int64
 20  MOTOCICLETA      130823 non-null  int64
 21  TRACAOANIMAL     130823 non-null  int64
 22  TREM             130823 non-null  int64
 23  DIA_SEMANA       130823 non-null  category
 24  FIM_DE_SEMANA    130823 non-null  bool
 25  FAIXA_HORARIA    130823 non-null  category
 26  TOTAL_VITIMAS    130823 non-null  int64
 27  TOTAL_VEICULOS   130823 non-null  int64
dtypes: bool(1), category(8), datetime64[ns](1), float64(2), int64(14), object(1), string(1)
memory usage: 20.1+ MB

In [121]:
df.describe()

,DATA E HORA,LATITUDE,LONGITUDE,MORTOS,FERIDOS,ILESOS,AUTOMOVEL,ONIBUS,BICICLETA,CAMINHAO,MICROONIBUS,CICLOMOTOR,MOTOCICLETA,TRACAOANIMAL,TREM,TOTAL_VITIMAS,TOTAL_VEICULOS
count,130823,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.000000,130823.00000,130823.000000,130823.000000
mean,2019-07-09 01:55:55.466141440,-3.767022,-38.539138,0.015181,1.069758,0.527721,0.838056,0.048822,0.043524,0.029720,0.005756,0.004418,0.648212,0.000099,0.00042,1.084939,1.619027
min,2015-01-01 00:11:00,-3.896179,-38.637996,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,2016-10-27 16:07:30,-3.793945,-38.570794,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,1.000000
50%,2019-02-09 06:40:00,-3.760579,-38.539369,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,1.000000,2.000000
75%,2022-03-18 12:55:54,-3.736271,-38.506470,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,1.000000,2.000000
max,2024-12-31 23:07:56,-3.693333,-38.410074,3.000000,26.000000,8.000000,12.000000,3.000000,3.000000,4.000000,2.000000,2.000000,6.000000,1.000000,1.00000,26.000000,19.000000
std,NaN,0.037304,0.039769,0.126089,0.702956,0.819732,0.773450,0.218945,0.204447,0.173949,0.075952,0.066553,0.610408,0.009968,0.02050,0.700728,0.729242

In [122]:
df.describe(include=["category", "bool"])

,BAIRRO,TIPOCRUZAMENTO,CONTROLETRAFEGO,USOSOLO,NATUREZA,SEVERIDADE,DIA_SEMANA,FIM_DE_SEMANA,FAIXA_HORARIA
count,130749,130823,130823,130823,130823,130823,130823,130823,130823
unique,121,14,16,3,20,4,7,2,4
top,Centro,Meio de Quadra,Não informado,Longo da via,Colisão,Ferido,Sexta,False,Tarde
freq,7418,48457,78372,63227,58544,94599,20681,95051,45401

### Salvar

Em `.parquet`, que preserva os tipos (datas e categorias); um `.csv` os perderia.

In [125]:
caminho_preparada = "/content/drive/MyDrive/analise_sinistros_transito_amc/Análises/0. Dataset/1_sinistros_transito_2015_2024_preparada.parquet"

df.to_parquet(caminho_preparada, index=False)

## 7. Dicionário de Dados (depois da limpeza)

Base preparada: `dataset/1_sinistros_transito_2015_2024_preparada.parquet`: 130.823 linhas, 28 colunas.
Cada linha é um sinistro de trânsito registrado em Fortaleza entre 2015 e 2024.

### Identificação, tempo e local

| Coluna | Tipo | Classificação | Descrição | Valores |
|---|---|---|---|---|
| `COD_ACIDENTE` | texto | Identificador | Código único do sinistro. Numérico até 2020 e alfanumérico a partir de 2021. | 130.820 códigos distintos; 3 vazios |
| `DATA E HORA` | data e hora | Quantitativa contínua (temporal) | Momento do sinistro. Criada a partir de `DIA`, `MES`, `ANO` e `HORA`. | 01/01/2015 00:11 a 31/12/2024 23:07 |
| `BAIRRO` | categoria | Qualitativa nominal | Bairro de Fortaleza onde o ponto está. Derivado de `LATITUDE` e `LONGITUDE`. | 121 bairros; 74 vazios (pontos fora do município) |
| `RUA` | texto | Qualitativa nominal | Via mais próxima do ponto. Derivada de `LATITUDE` e `LONGITUDE`. | 4.127 vias distintas |
| `LATITUDE` | decimal | Quantitativa contínua | Latitude do sinistro, em graus decimais. | -3,896 a -3,693 |
| `LONGITUDE` | decimal | Quantitativa contínua | Longitude do sinistro, em graus decimais. | -38,638 a -38,410 |

### Características do sinistro

| Coluna | Tipo | Classificação | Descrição | Valores |
|---|---|---|---|---|
| `TIPOCRUZAMENTO` | categoria | Qualitativa nominal | Configuração da via no local. | 10 categorias (ex.: Meio de quadra, Cruz, T, Rotatória); 12,46% "Não informado" |
| `CONTROLETRAFEGO` | categoria | Qualitativa nominal | Controle de tráfego existente no local. | 13 categorias (ex.: Pare, Semáforo, Não há controle); 59,91% "Não informado" |
| `USOSOLO` | categoria | Qualitativa nominal | Posição do sinistro em relação à via. | Longo da via, Cruzamento, Não informado (21,80%) |
| `NATUREZA` | categoria | Qualitativa nominal | Tipo de sinistro. | 20 categorias (ex.: Colisão, Queda, Atropelamento); 0,96% "Não informado" |
| `SEVERIDADE` | categoria | Qualitativa ordinal | Gravidade do sinistro. | Ileso, Ferido, Fatal, Não informado (7,06%) |

### Pessoas envolvidas

| Coluna | Tipo | Classificação | Descrição | Valores |
|---|---|---|---|---|
| `MORTOS` | inteiro | Quantitativa discreta | Número de mortos no sinistro. | 0 a 3 |
| `FERIDOS` | inteiro | Quantitativa discreta | Número de feridos no sinistro. | 0 a 26 |
| `ILESOS` | inteiro | Quantitativa discreta | Número de envolvidos sem ferimentos. | 0 a 8 |

### Veículos envolvidos

Cada coluna traz a quantidade de veículos daquele tipo no sinistro.

| Coluna | Tipo | Classificação | Descrição | Valores |
|---|---|---|---|---|
| `AUTOMOVEL` | inteiro | Quantitativa discreta | Automóveis. | 0 a 12 |
| `ONIBUS` | inteiro | Quantitativa discreta | Ônibus. | 0 a 3 |
| `BICICLETA` | inteiro | Quantitativa discreta | Bicicletas. | 0 a 3 |
| `CAMINHAO` | inteiro | Quantitativa discreta | Caminhões. | 0 a 4 |
| `MICROONIBUS` | inteiro | Quantitativa discreta | Micro-ônibus. | 0 a 2 |
| `CICLOMOTOR` | inteiro | Quantitativa discreta | Ciclomotores. | 0 a 2 |
| `MOTOCICLETA` | inteiro | Quantitativa discreta | Motocicletas. | 0 a 6 |
| `TRACAOANIMAL` | inteiro | Quantitativa discreta | Veículos de tração animal. | 0 a 1 |
| `TREM` | inteiro | Quantitativa discreta | Trens. | 0 a 1 |

### Variáveis criadas na preparação

| Coluna | Tipo | Classificação | Descrição | Valores |
|---|---|---|---|---|
| `DIA_SEMANA` | categoria | Qualitativa ordinal | Dia da semana de `DATA E HORA`. | Segunda a Domingo |
| `FIM_DE_SEMANA` | booleano | Qualitativa nominal (binária) | Indica se o sinistro ocorreu em sábado ou domingo. | `True` (27,34%) ou `False` |
| `FAIXA_HORARIA` | categoria | Qualitativa ordinal | Período do dia de `DATA E HORA`. | Madrugada (0h–5h59), Manhã (6h–11h59), Tarde (12h–17h59), Noite (18h–23h59) |
| `TOTAL_VITIMAS` | inteiro | Quantitativa discreta | `MORTOS` + `FERIDOS`. | 0 a 26 |
| `TOTAL_VEICULOS` | inteiro | Quantitativa discreta | Soma das nove colunas de veículos. | 0 a 19 |

### Observações

- As categorias foram padronizadas na seção 6: grafias diferentes do mesmo valor (ex.: `Meio de Quadra`, `Meio De Quadra`, `Meio de quadra`) viraram uma só.
- "Não informado" é um valor preenchido, não uma célula vazia.

## 8. Análise univariada

In [126]:
caminho_drive = '/content/drive/MyDrive/analise_sinistros_transito_amc/Análises/0. Dataset/1_sinistros_transito_2015_2024_preparada.parquet'
df = pd.read_parquet(caminho_drive)

## 9. Análise bivariada

## 10. Análise multivariada

## 11. Testes de hipótese

## 12. Conclusões